import React from "react";
import "./Component Styles/DTP_Subdetails.css";
import {Format_Money} from "./Utils.js"

export default function DTP_Subdetails({ Detailed_Item }) {

  return (
    <div className="sub-details">
      <div className="item-photo">
        <img className="flag-photo" src={Detailed_Item[0].flag} alt="" /><br />
        <hr />
        <b>Ülke: </b> {Detailed_Item[0].main_country} <br />
        <hr />
        <b>Teklif Kodu: </b> {Detailed_Item[0].key}<br />
        <hr />
        <b>Sirket İsmi: </b> {Detailed_Item[0].name} <br />
        <hr />
        <b>Teklif: </b> {Format_Money(Detailed_Item[0].amount)}<br />
        <hr />
        <b>Aktiflik Durumu: </b>{Detailed_Item[0].state} <br />
        <hr />
        <b>Aranan İş: </b>{Detailed_Item[0].job_type} <br />
        <hr />
        <b>İş Deneyimi: </b> {Detailed_Item[0].experience} yıl
        <hr />
      </div>
      <div className="item-details">
        <h1>ÖRNEK YAZIDIR...</h1>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Arcu bibendum at varius vel pharetra vel turpis. Amet justo donec enim diam vulputate ut. Nunc mattis enim ut tellus elementum. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Convallis tellus id interdum velit. Nunc faucibus a pellentesque sit amet porttitor. At quis risus sed vulputate odio ut. At quis risus sed vulputate odio ut enim blandit volutpat. Tellus integer feugiat scelerisque varius morbi enim nunc. Pharetra vel turpis nunc eget lorem dolor sed viverra. Tincidunt eget nullam non nisi est. Phasellus vestibulum lorem sed risus ultricies tristique nulla. Aliquam nulla facilisi cras fermentum. Aliquam ut porttitor leo a diam sollicitudin tempor. Tortor posuere ac ut consequat. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim tortor. Etiam tempor orci eu lobortis elementum nibh tellus molestie nunc. Ut aliquam purus sit amet luctus venenatis lectus magna.

Et malesuada fames ac turpis egestas sed. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Aliquet sagittis id consectetur purus ut faucibus. Enim lobortis scelerisque fermentum dui faucibus in. Magna etiam tempor orci eu. Cras fermentum odio eu feugiat. Tortor posuere ac ut consequat semper viverra nam. Erat imperdiet sed euismod nisi porta. Imperdiet sed euismod nisi porta. Ipsum a arcu cursus vitae congue mauris rhoncus aenean. Nibh sit amet commodo nulla facilisi nullam. Faucibus turpis in eu mi bibendum neque. Auctor elit sed vulputate mi. Molestie nunc non blandit massa enim nec. Et sollicitudin ac orci phasellus egestas tellus rutrum. Interdum velit euismod in pellentesque massa placerat. Adipiscing diam donec adipiscing tristique risus nec feugiat.

Enim sed faucibus turpis in eu mi bibendum. Elementum nibh tellus molestie nunc. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Facilisis gravida neque convallis a cras. Aliquet eget sit amet tellus. Vel elit scelerisque mauris pellentesque. In massa tempor nec feugiat nisl pretium fusce id. Turpis cursus in hac habitasse platea dictumst quisque sagittis purus. Pharetra massa massa ultricies mi quis hendrerit dolor magna. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Elit ut aliquam purus sit amet luctus. Scelerisque felis imperdiet proin fermentum. Ut venenatis tellus in metus vulputate.

Turpis tincidunt id aliquet risus feugiat in. Quis eleifend quam adipiscing vitae proin sagittis. Bibendum enim facilisis gravida neque convallis a cras. Sit amet risus nullam eget felis eget nunc lobortis. Varius sit amet mattis vulputate enim nulla. Cras semper auctor neque vitae tempus quam pellentesque nec. Quis commodo odio aenean sed adipiscing diam donec. Quisque sagittis purus sit amet volutpat consequat mauris. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Ultrices eros in cursus turpis massa tincidunt dui. Quam adipiscing vitae proin sagittis nisl rhoncus mattis. Morbi leo urna molestie at elementum eu facilisis sed. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Velit sed ullamcorper morbi tincidunt ornare. Duis at tellus at urna condimentum mattis pellentesque id. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Mi in nulla posuere sollicitudin. Duis at tellus at urna condimentum. Odio ut enim blandit volutpat maecenas volutpat blandit.

Risus viverra adipiscing at in tellus integer feugiat scelerisque varius. Erat imperdiet sed euismod nisi porta. Nulla facilisi etiam dignissim diam. Lacus luctus accumsan tortor posuere ac ut consequat semper. Turpis egestas integer eget aliquet nibh. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. In eu mi bibendum neque egestas congue quisque egestas. Rhoncus aenean vel elit scelerisque mauris pellentesque. Pellentesque habitant morbi tristique senectus. Netus et malesuada fames ac turpis egestas maecenas. Magna eget est lorem ipsum dolor sit amet consectetur. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Quisque egestas diam in arcu cursus euismod quis. Vitae justo eget magna fermentum iaculis. Tortor condimentum lacinia quis vel eros donec ac odio. Scelerisque eu ultrices vitae auctor eu augue ut.

Sed sed risus pretium quam vulputate dignissim. Et ultrices neque ornare aenean euismod. Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Congue eu consequat ac felis donec et. Amet purus gravida quis blandit. Nisi porta lorem mollis aliquam ut porttitor leo. Imperdiet proin fermentum leo vel orci porta. Imperdiet proin fermentum leo vel orci porta non pulvinar. Turpis egestas maecenas pharetra convallis posuere morbi leo. Amet cursus sit amet dictum sit amet justo donec. Faucibus ornare suspendisse sed nisi. Porta nibh venenatis cras sed felis eget velit aliquet. Tincidunt eget nullam non nisi est. Enim neque volutpat ac tincidunt. Lorem sed risus ultricies tristique nulla aliquet. Venenatis urna cursus eget nunc scelerisque viverra mauris in aliquam. Eget arcu dictum varius duis at. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu.

Congue mauris rhoncus aenean vel elit. Eu volutpat odio facilisis mauris sit. Ac auctor augue mauris augue neque gravida in. Fermentum odio eu feugiat pretium nibh ipsum. Sed libero enim sed faucibus turpis in eu mi bibendum. Diam maecenas ultricies mi eget. Consectetur libero id faucibus nisl tincidunt eget nullam non nisi. Adipiscing elit pellentesque habitant morbi tristique. Quis lectus nulla at volutpat diam ut venenatis. Semper quis lectus nulla at volutpat diam ut venenatis. In cursus turpis massa tincidunt dui. Maecenas accumsan lacus vel facilisis volutpat est. Eget duis at tellus at urna condimentum mattis. Nunc lobortis mattis aliquam faucibus purus in massa tempor nec. Adipiscing bibendum est ultricies integer quis auctor elit sed.

Aliquam nulla facilisi cras fermentum odio. Sagittis orci a scelerisque purus semper. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Elit sed vulputate mi sit. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Sit amet nisl suscipit adipiscing. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Amet dictum sit amet justo donec enim. Libero justo laoreet sit amet cursus sit amet. Adipiscing commodo elit at imperdiet dui. Convallis a cras semper auctor neque vitae tempus quam pellentesque. Vitae justo eget magna fermentum iaculis eu. Euismod nisi porta lorem mollis aliquam. Netus et malesuada fames ac turpis egestas integer eget. Enim facilisis gravida neque convallis a cras semper. Interdum velit laoreet id donec.

Sit amet porttitor eget dolor morbi non arcu. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Habitant morbi tristique senectus et. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Mi bibendum neque egestas congue quisque egestas. Imperdiet dui accumsan sit amet nulla facilisi. Sit amet luctus venenatis lectus magna. Dui nunc mattis enim ut tellus. Fusce id velit ut tortor pretium. Morbi enim nunc faucibus a pellentesque sit amet porttitor. Iaculis urna id volutpat lacus laoreet non curabitur. Magna fringilla urna porttitor rhoncus dolor purus. Aliquet nibh praesent tristique magna sit amet purus gravida. Egestas congue quisque egestas diam in. Morbi leo urna molestie at elementum. Vivamus arcu felis bibendum ut. At volutpat diam ut venenatis. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Dignissim convallis aenean et tortor at risus viverra adipiscing. Sed felis eget velit aliquet sagittis id consectetur purus.

Lacinia quis vel eros donec ac odio tempor. Id diam vel quam elementum pulvinar. Tempus urna et pharetra pharetra. Volutpat odio facilisis mauris sit amet massa vitae. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Leo integer malesuada nunc vel risus commodo. Et molestie ac feugiat sed lectus vestibulum mattis. Tempus urna et pharetra pharetra massa massa. Id volutpat lacus laoreet non curabitur gravida arcu. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Aliquet risus feugiat in ante metus dictum at tempor commodo. Velit dignissim sodales ut eu sem. Vitae auctor eu augue ut lectus arcu bibendum at. Quisque sagittis purus sit amet volutpat consequat mauris.

Purus non enim praesent elementum facilisis leo. Lorem ipsum dolor sit amet consectetur adipiscing. In nulla posuere sollicitudin aliquam ultrices sagittis orci a. A erat nam at lectus urna. In mollis nunc sed id semper. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis. Sed tempus urna et pharetra pharetra massa massa. Sed lectus vestibulum mattis ullamcorper. Est ullamcorper eget nulla facilisi etiam dignissim diam. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra. At risus viverra adipiscing at in tellus. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Id cursus metus aliquam eleifend mi in nulla. Est ultricies integer quis auctor elit. Mi bibendum neque egestas congue quisque. Euismod lacinia at quis risus sed. Ut tortor pretium viverra suspendisse. Turpis egestas pretium aenean pharetra magna ac. Ac felis donec et odio.

Cras sed felis eget velit aliquet sagittis id. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Nisi porta lorem mollis aliquam. Sodales ut eu sem integer vitae justo eget magna. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Netus et malesuada fames ac turpis egestas maecenas pharetra. Morbi non arcu risus quis varius quam. Augue ut lectus arcu bibendum at varius. Lacus sed viverra tellus in hac. Blandit cursus risus at ultrices mi tempus imperdiet nulla. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Dignissim diam quis enim lobortis scelerisque fermentum dui. Velit sed ullamcorper morbi tincidunt ornare massa.

Et leo duis ut diam quam nulla porttitor massa id. Sociis natoque penatibus et magnis. Imperdiet sed euismod nisi porta lorem mollis. Tincidunt id aliquet risus feugiat in ante metus. Rhoncus urna neque viverra justo nec ultrices dui sapien. Aenean pharetra magna ac placerat vestibulum lectus mauris. Dignissim suspendisse in est ante in nibh mauris cursus mattis. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Neque laoreet suspendisse interdum consectetur. Volutpat consequat mauris nunc congue nisi. Id diam vel quam elementum pulvinar etiam. Nunc congue nisi vitae suscipit tellus mauris.

Sit amet aliquam id diam. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Nisl rhoncus mattis rhoncus urna. Purus in massa tempor nec feugiat nisl. Enim facilisis gravida neque convallis a. Facilisi nullam vehicula ipsum a. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Id nibh tortor id aliquet lectus. Volutpat lacus laoreet non curabitur gravida arcu ac. Purus semper eget duis at tellus at urna condimentum. Orci phasellus egestas tellus rutrum. Volutpat odio facilisis mauris sit. Euismod quis viverra nibh cras.

Eu consequat ac felis donec et odio pellentesque diam. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Molestie at elementum eu facilisis sed odio morbi quis commodo. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Pellentesque habitant morbi tristique senectus et netus et. Porta non pulvinar neque laoreet suspendisse interdum. Odio tempor orci dapibus ultrices in. Senectus et netus et malesuada fames ac turpis egestas sed. Adipiscing at in tellus integer feugiat. Viverra justo nec ultrices dui sapien eget. Euismod lacinia at quis risus sed vulputate odio ut. Sit amet purus gravida quis blandit. Viverra nibh cras pulvinar mattis nunc sed blandit. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. Facilisis gravida neque convallis a. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Eget velit aliquet sagittis id consectetur purus ut.

Pulvinar elementum integer enim neque volutpat ac tincidunt vitae semper. Purus gravida quis blandit turpis cursus in hac habitasse platea. Massa eget egestas purus viverra accumsan in nisl nisi. Consectetur a erat nam at lectus urna duis. Tempus quam pellentesque nec nam. Dignissim suspendisse in est ante in. Scelerisque in dictum non consectetur a erat nam at lectus. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. In mollis nunc sed id semper risus in hendrerit. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit amet. Volutpat odio facilisis mauris sit. Turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet.

Ut ornare lectus sit amet est placerat in egestas erat. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Sit amet massa vitae tortor condimentum lacinia quis vel. Odio morbi quis commodo odio aenean sed adipiscing diam. Non curabitur gravida arcu ac tortor dignissim convallis aenean et. Augue mauris augue neque gravida in fermentum. Ultrices sagittis orci a scelerisque purus semper eget duis. Aenean et tortor at risus viverra adipiscing at in. Pellentesque habitant morbi tristique senectus et netus et. Sit amet nisl purus in mollis nunc sed id.

Eu lobortis elementum nibh tellus molestie nunc non. Diam donec adipiscing tristique risus nec feugiat in fermentum posuere. Phasellus vestibulum lorem sed risus. Facilisi cras fermentum odio eu. Leo vel orci porta non pulvinar neque. Commodo elit at imperdiet dui accumsan sit amet nulla. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Senectus et netus et malesuada fames. Imperdiet sed euismod nisi porta lorem. Adipiscing vitae proin sagittis nisl rhoncus. Vitae semper quis lectus nulla at. Proin fermentum leo vel orci porta non pulvinar neque. Urna duis convallis convallis tellus id interdum velit laoreet id. Magna eget est lorem ipsum dolor sit. Id porta nibh venenatis cras sed.

Et tortor consequat id porta. Amet volutpat consequat mauris nunc congue nisi. Semper auctor neque vitae tempus quam pellentesque nec. Posuere ac ut consequat semper viverra. Quam pellentesque nec nam aliquam sem. Non curabitur gravida arcu ac tortor dignissim convallis. Aliquam sem et tortor consequat id. Neque viverra justo nec ultrices dui sapien eget mi proin. Donec pretium vulputate sapien nec sagittis. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Libero id faucibus nisl tincidunt eget nullam. In cursus turpis massa tincidunt dui ut. A cras semper auctor neque vitae tempus quam pellentesque nec. Rhoncus est pellentesque elit ullamcorper. Aliquam vestibulum morbi blandit cursus risus at ultrices.

Pulvinar pellentesque habitant morbi tristique senectus et. Volutpat blandit aliquam etiam erat velit scelerisque in dictum non. Lobortis feugiat vivamus at augue. Amet cursus sit amet dictum sit amet. Facilisis volutpat est velit egestas dui id ornare. Eget nulla facilisi etiam dignissim diam. Feugiat nibh sed pulvinar proin gravida. A condimentum vitae sapien pellentesque habitant. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Viverra accumsan in nisl nisi scelerisque eu ultrices vitae. Lobortis scelerisque fermentum dui faucibus in ornare quam. Congue mauris rhoncus aenean vel elit scelerisque mauris. Est ante in nibh mauris cursus mattis. Sit amet nisl purus in. Ultrices sagittis orci a scelerisque purus semper eget.

Adipiscing elit pellentesque habitant morbi tristique. Mauris rhoncus aenean vel elit scelerisque mauris. Amet massa vitae tortor condimentum lacinia quis vel eros. Massa tincidunt nunc pulvinar sapien et ligula. Cum sociis natoque penatibus et magnis dis parturient. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Quis commodo odio aenean sed. Non pulvinar neque laoreet suspendisse interdum consectetur. Lorem dolor sed viverra ipsum nunc aliquet. Vehicula ipsum a arcu cursus. Sed ullamcorper morbi tincidunt ornare. Libero volutpat sed cras ornare arcu. Dignissim enim sit amet venenatis urna cursus.

Aliquam malesuada bibendum arcu vitae elementum curabitur. Blandit turpis cursus in hac. Fermentum dui faucibus in ornare quam viverra orci. Amet nulla facilisi morbi tempus iaculis urna. Etiam tempor orci eu lobortis elementum. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Vel risus commodo viverra maecenas accumsan lacus vel facilisis. Purus non enim praesent elementum facilisis leo. Nunc consequat interdum varius sit amet mattis vulputate enim. Netus et malesuada fames ac.

Sociis natoque penatibus et magnis dis parturient montes. Tempor commodo ullamcorper a lacus vestibulum sed arcu. Orci a scelerisque purus semper. Aliquet nec ullamcorper sit amet risus nullam eget felis eget. Viverra maecenas accumsan lacus vel facilisis. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Euismod in pellentesque massa placerat duis ultricies lacus. Elit eget gravida cum sociis natoque penatibus et magnis. Ut diam quam nulla porttitor massa id neque aliquam. Neque egestas congue quisque egestas. Semper auctor neque vitae tempus quam pellentesque nec nam aliquam. Id interdum velit laoreet id donec ultrices tincidunt arcu. Euismod nisi porta lorem mollis aliquam ut porttitor leo a. Convallis posuere morbi leo urna molestie at.

Eget felis eget nunc lobortis. Viverra tellus in hac habitasse platea. Arcu non odio euismod lacinia at quis risus. In massa tempor nec feugiat nisl pretium. Tincidunt id aliquet risus feugiat in ante metus dictum at. A erat nam at lectus urna. Ut venenatis tellus in metus vulputate eu scelerisque felis. Dui ut ornare lectus sit amet est placerat in. Quisque egestas diam in arcu cursus. Ridiculus mus mauris vitae ultricies leo. Auctor eu augue ut lectus arcu bibendum. Enim diam vulputate ut pharetra sit amet aliquam. Semper feugiat nibh sed pulvinar proin. Eget mauris pharetra et ultrices neque ornare. Quis hendrerit dolor magna eget est lorem ipsum. Lacinia at quis risus sed vulputate odio. In eu mi bibendum neque egestas. In mollis nunc sed id semper risus in hendrerit.

Placerat vestibulum lectus mauris ultrices eros in cursus. Blandit aliquam etiam erat velit scelerisque. Ac feugiat sed lectus vestibulum mattis. Facilisi etiam dignissim diam quis enim lobortis. At imperdiet dui accumsan sit amet nulla facilisi morbi. Convallis aenean et tortor at risus. Dui ut ornare lectus sit amet est placerat. Mauris augue neque gravida in. Amet cursus sit amet dictum sit amet justo donec. Nunc non blandit massa enim nec dui nunc mattis. Elit duis tristique sollicitudin nibh sit amet commodo nulla. Nunc congue nisi vitae suscipit tellus.

Consectetur purus ut faucibus pulvinar elementum integer. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Senectus et netus et malesuada fames ac turpis egestas. Aliquam ut porttitor leo a diam sollicitudin tempor id. Et leo duis ut diam quam nulla porttitor. Nunc non blandit massa enim. Id diam vel quam elementum pulvinar etiam non. Lobortis mattis aliquam faucibus purus in massa tempor nec feugiat. Sit amet tellus cras adipiscing enim. Nisl nisi scelerisque eu ultrices vitae auctor. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Consectetur a erat nam at lectus urna duis convallis. Est ultricies integer quis auctor. Congue nisi vitae suscipit tellus mauris. Pulvinar mattis nunc sed blandit. Pretium fusce id velit ut.

Mattis nunc sed blandit libero volutpat sed cras ornare. Et odio pellentesque diam volutpat commodo. Aliquet lectus proin nibh nisl condimentum id venenatis a condimentum. Imperdiet proin fermentum leo vel. Neque vitae tempus quam pellentesque nec nam aliquam. Semper viverra nam libero justo. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a. In hac habitasse platea dictumst quisque sagittis purus sit. Consectetur adipiscing elit ut aliquam. Facilisis sed odio morbi quis commodo odio aenean sed adipiscing. Arcu cursus vitae congue mauris rhoncus aenean. Adipiscing elit duis tristique sollicitudin nibh sit. Egestas integer eget aliquet nibh praesent tristique magna. Ut faucibus pulvinar elementum integer enim. Velit aliquet sagittis id consectetur purus. Bibendum est ultricies integer quis auctor elit sed. Ipsum a arcu cursus vitae congue mauris rhoncus. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. Tincidunt lobortis feugiat vivamus at.

Blandit libero volutpat sed cras ornare arcu. Tristique nulla aliquet enim tortor at auctor urna. Pulvinar etiam non quam lacus. Ipsum consequat nisl vel pretium lectus quam id leo in. Venenatis tellus in metus vulputate eu scelerisque. Velit euismod in pellentesque massa placerat duis ultricies lacus. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Magna ac placerat vestibulum lectus. Vestibulum mattis ullamcorper velit sed. Netus et malesuada fames ac turpis egestas sed. Ac odio tempor orci dapibus. Nisi est sit amet facilisis magna etiam tempor orci eu. Pretium nibh ipsum consequat nisl vel pretium lectus quam. Adipiscing diam donec adipiscing tristique risus nec feugiat. Leo vel orci porta non. Aliquet enim tortor at auctor urna. Cursus turpis massa tincidunt dui ut ornare lectus sit. Libero id faucibus nisl tincidunt. Ac turpis egestas maecenas pharetra convallis posuere morbi.

Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Eget mauris pharetra et ultrices neque ornare. Ac ut consequat semper viverra nam libero justo. Consequat id porta nibh venenatis cras sed. Diam donec adipiscing tristique risus nec feugiat in fermentum posuere. Nulla facilisi morbi tempus iaculis. In iaculis nunc sed augue lacus viverra. Mi sit amet mauris commodo quis imperdiet massa tincidunt. Morbi tristique senectus et netus et malesuada. Laoreet non curabitur gravida arcu ac tortor.

Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Eu mi bibendum neque egestas. Elit ut aliquam purus sit amet luctus. Massa ultricies mi quis hendrerit dolor magna eget est. Dictumst quisque sagittis purus sit. Nec ultrices dui sapien eget mi proin sed libero enim. A iaculis at erat pellentesque. Id ornare arcu odio ut sem nulla pharetra diam. Non sodales neque sodales ut etiam sit amet nisl. Tincidunt id aliquet risus feugiat in ante metus. Egestas quis ipsum suspendisse ultrices gravida dictum. Est ante in nibh mauris cursus mattis molestie a iaculis. Eget mi proin sed libero enim. Aenean sed adipiscing diam donec adipiscing tristique.
      </div>
      
    </div>
  );
}
